### PR TITLE
Support missing contriburl arg

### PR DESCRIPTION
**Pull request by krlmlr**
for running with `R --vanilla`.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
So how does this come up?

**Comment by krlmlr** [comment]
When I try `R --vanilla -q -e 'revdepcheck::revdep_check(...)'`

**Comment by gaborcsardi** [comment]
Yeah, but why is `contiburl` missing then?

**Comment by krlmlr** [comment]
Because revdepcheck never passes it explicitly.

**Comment by gaborcsardi** [comment]
It passed the missing argument explicitly? 

Sorry, I am just trying to understand.

**Comment by krlmlr** [comment]
Seems superseded by https://github.com/r-lib/revdepcheck/pull/50.

**Pull request closed without merging**
